export const courses = [
  {
    id: 1,
    title: "Machine Learning Basics",
    instructor: "Jennifer Anderson",
    rating: 5,
    image: "/images/course1.jpg",
    category: "Graphic Design",
  },
  {
    id: 2,
    title: "Business Analytics & Strategy",
    instructor: "Robert Chen",
    rating: 5,
    image: "/images/course2.jpg",
    category: "UI/UX Design",
  },
  {
    id: 3,
    title: "Content Marketing",
    instructor: "Emily Davis",
    rating: 5,
    image: "/images/course3.jpg",
    category: "Brand Identity",
  },
  {
    id: 4,
    title: "Product Design for Beginner",
    instructor: "Michael Torres",
    rating: 5,
    image: "/images/course4.jpg",
    category: "Web Design",
  },
  {
    id: 5,
    title: "Backend Developer",
    instructor: "Sarah Williams",
    rating: 4,
    image: "/images/course5.jpg",
    category: "Development",
  },
  {
    id: 6,
    title: "Adobe XD for Designer",
    instructor: "David Martinez",
    rating: 5,
    image: "/images/course6.jpg",
    category: "Design",
  },
];